apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic-up14
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/anjoseph-tenant/my-app/devfile-sample-go-basic-up14@sha256:0e4b1b4d7fe1828c8a89c0dbc5eacece284a7f720ef2d204709178b7c33b31af
        name: my-go
        resources: {}
status: {}
