apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic-up14
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/anjoseph-tenant/my-app/devfile-sample-go-basic-up14@sha256:02c6ec47456e0be43292ef5d2e874316355bdba165798e9791d3291a7a9d1eae
        name: my-go
        resources: {}
status: {}
